url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "public.bot" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss
  - jekyll-datapage-generator

postcss:
  cache: false

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

page_gen:
  - data: 'states'
    template: 'generated_page'
    name_expr: record["attributes"]['STUSPS']
    dir: 'jurisdictions/states'
  - data: 'counties'
    template: 'generated_page'
    name_expr: record["attributes"]['state_abbreviation'] + "-" + record["attributes"]['NAMELSAD']
    dir: 'jurisdictions/counties'
